#!/bin/sh
# 
# bin/noawl, DESCRIPTION
# 
# Copyright (C) 2003 Jonathan J. Miner
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# $Id:$
# Jonathan J. Miner <miner@doit.wisc.edu>

if test -z "$1"; then
    echo Usage: $0 addr-to-blacklist
    exit
fi

spamassassin --remove-addr-from-whitelist $1
spamassassin --add-addr-to-blacklist $1
