#!/bin/sh
# 
# genfilt, Generic Filter
# 
# Copyright (C) 2000 Jonathan J. Miner
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# $Id:$
# Jonathan J. Miner <miner@doit.wisc.edu>

prog=${0##*/}

file=$1;

type=`file $file | cut -d ' ' -f 2-`

echo $file $type

case "$type" in
    *image*) xv $file;;
    'Microsoft Office Document')
        base=`basename $file`
        suffix=`echo $base | sed 's/.*\.//'`
        echo "Base: $base Suffix: $suffix"
        case "$suffix" in
            xls) excel2text $file;;
            doc) word2text $file
        esac
    ;;
    *text*)
        base=`basename $file`
        suffix=`echo $base | sed 's/.*\.//'`
        echo "Base: $base Suffix: $suffix"
        case "$suffix" in
            vcf | VCF) cat $file | mutt.vcard.filter ;;
            csr | CSR) openssl req -text -in $file ;;
            crt | CRT | pem | PEM) openssl x509 -text - in $file ;;
            *)  less $file;;
        esac
        ;;
    MPEG*) xanim $file;;
    "ASCII*") less $file;;
    *)
        base=`basename $file`
        suffix=`echo $base | sed 's/.*\.//'`
        echo "Base: $base Suffix: $suffix"
        case "$suffix" in
            vcf | VCF) cat $file | mutt.vcard.filter ;;
            *) echo $type; cat > /dev/null ;;
        esac
    ;;
esac
