#!/bin/sh
# 
# bin/killnewmail, DESCRIPTION
# 
# Copyright (C) 2002 Jonathan J. Miner
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# $Id:$
# Jonathan J. Miner <miner@doit.wisc.edu>

TTY=`tty | sed 's#.*\(pts/.*\)#\1#'`
PS=`ps | grep $TTY | grep '\<newmail\>'`
PID=`echo $PS | awk '{ print $1}'`

if test "x$PID" != "x" ; then
    echo Killing newmail: $PID
    kill $PID
fi
