#!/bin/sh
# 
# bin/page, DESCRIPTION
# 
# Copyright (C) 2003 Jonathan J. Miner
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# $Id:$
# Jonathan J. Miner <miner@doit.wisc.edu>

case "$1" in
    on)
        rm -f $HOME/.nopage
        rm -f $HOME/.disableidle
        ;;
    off)
        date > $HOME/.nopage
        ;;
    always)
        rm -f $HOME/.nopage
        rm -f $HOME/.notidle
        date > $HOME/.disableidle
        ;;
    status)
        if test -f $HOME/.nopage; then
            echo "Paging disabled since "`cat $HOME/.nopage`
        else
            echo "Paging enabled"
            if test -f $HOME/.disableidle; then
                echo "Paging always since "`cat $HOME/.disableidle`
            fi
        fi
        ;;
    *)
        echo "usage: page [on|off|status]"
        echo "       sets or checks paging status."
        ;;
esac
