#!/usr/bin/perl
#
#

$head = 1;
while( <> ) {
    $head = 0 if ( /^$/ );
    if ($head && s/^Subject:\s*(.*) -Reply/\1/i) {
        s/Re:[ ]?(.*)/\1/i;
        s/^/Subject: Re: /;
    }
    print $_;
}
